---
sidebar: sidebar 
permalink: concept-privacy.html 
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault 
summary: NetApp no tiene acceso a ninguna credencial que proporcione mientras utiliza el servicio Cloud Sync. Las credenciales se almacenan directamente en el equipo de Data broker, que reside en la red. 
---
= Privacidad de datos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp no tiene acceso a ninguna credencial que proporcione mientras utiliza el servicio Cloud Sync. Las credenciales se almacenan directamente en el equipo de Data broker, que reside en la red.

Según la configuración seleccionada, Cloud Sync puede pedirle credenciales cuando cree una nueva relación. Por ejemplo, cuando se configura una relación que incluye un servidor SMB o cuando se implementa el agente de datos en AWS.

Estas credenciales siempre se guardan directamente en el propio agente de datos. El agente de datos reside en un equipo de su red, ya sea en las instalaciones o en su cuenta de cloud. NetApp nunca pone a disposición de estas credenciales.

Las credenciales se cifran localmente en la máquina de corredores de datos utilizando HashiCorp Vault.
