---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es el pago por uso. La segunda opción consiste en comprar licencias directamente a NetApp. 
---
= Pago de las relaciones de sincronización después de que finalice su prueba gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay dos formas de pagar las relaciones de sincronización después de que termine su prueba gratuita de 14 días. La primera opción es suscribirse a AWS o Azure para pagar por uso o anualmente. La segunda opción consiste en comprar licencias directamente a NetApp.

Puede suscribirse desde el AWS Marketplace o desde Azure Marketplace. No puede suscribirse de ambos.

Puede utilizar licencias de NetApp con una suscripción a Marketplace. Por ejemplo, si tiene 25 relaciones de sincronización, puede pagar las primeras 20 relaciones de sincronización con una licencia y, a continuación, pagar por el uso desde AWS o Azure con las 5 relaciones de sincronización restantes.

link:concept-licensing.html["Obtenga más información sobre cómo funcionan las licencias"].

Si usted no paga inmediatamente después de que su prueba gratuita termina, usted no podrá crear ninguna relación adicional. Las relaciones existentes no se eliminan, pero no puede realizar ningún cambio hasta que se suscriba o introduzca una licencia.

Las licencias se deben administrar a través de Cloud Sync o del sitio web correspondiente y *no* a través de una cartera digital.



== [[aws]]Suscribirse a AWS

AWS le permite pagar anualmente.

.De pago por uso
. Haga clic en *Sincronizar > licencias*.
. Seleccione *AWS*
. Haga clic en *Suscribirse* y, a continuación, en *continuar*.
. Suscríbase desde el mercado de AWS y, a continuación, vuelva a iniciar sesión en el servicio Cloud Sync para completar el registro.
+
El siguiente vídeo muestra el proceso:

+
video::video_cloud_sync_registering.mp4[width=848,height=480]


.Pasos a pagar anualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Vaya a la página AWS Marketplace"^].
. Haga clic en *continuar para suscribirse*.
. Seleccione sus opciones de contrato y haga clic en *Crear contrato*.




== [[Azure]]suscribirse de Azure

Azure le permite pagar por uso o anualmente.

.Lo que necesitará
Cuenta de usuario de Azure con permisos de colaborador o propietario en la suscripción correspondiente.

.Pasos
. Haga clic en *Sincronizar > licencias*.
. Seleccione *Azure*.
. Haga clic en *Suscribirse* y, a continuación, en *continuar*.
. En el portal de Azure, haga clic en *Crear*, seleccione sus opciones y haga clic en *Suscribirse*.
+
Seleccione *Mensual* para pagar por hora, o *Anual* para pagar por un año antes de la fecha.

. Una vez completada la implementación, haga clic en el nombre del recurso SaaS en la ventana emergente de notificaciones.
. Haga clic en *Configurar cuenta* para volver a Cloud Sync.
+
El siguiente vídeo muestra el proceso:

+
video::video_cloud_sync_registering_azure.mp4[width=848,height=480]




== [[licencias]]Compra de licencias de NetApp y añadirlas a Cloud Sync

Para pagar por adelantado sus relaciones de sincronización, debe adquirir una o más licencias y añadirlas al servicio de Cloud Sync.

.Lo que necesitará
Necesitará el número de serie de su licencia, así como el nombre de usuario y la contraseña de la cuenta del sitio de soporte de NetApp con la que está asociada la licencia.

.Pasos
. Adquiera una licencia por correo electrónico:ng-cloudsync-contact@netapp.com?Subject=Cloud%20Sync%20Service%20-%20BYOL%20Licencia%20Compra%20Solicite[Contacto con NetApp].
. En BlueXP, haga clic en *Sincronizar > licencias*.
. Haga clic en *Agregar licencia* y agregue la información necesaria:
+
.. Introduzca el número de serie.
.. Seleccione la cuenta del sitio de soporte de NetApp asociada con la licencia que va a añadir:
+
*** Si su cuenta ya se ha añadido a BlueXP, selecciónela en la lista desplegable.
*** Si aún no se ha agregado su cuenta, haga clic en *Agregar credenciales de NSS*, introduzca el nombre de usuario y la contraseña, haga clic en *Registro* y, a continuación, selecciónela en la lista desplegable.


.. Haga clic en *Agregar*.






== Actualizar una licencia

Si ha ampliado una licencia de Cloud Sync que ha comprado a NetApp, la nueva fecha de caducidad no se actualizará automáticamente en Cloud Sync. Debe volver a agregar la licencia para actualizar la fecha de caducidad. Las licencias se deben administrar a través de Cloud Sync o del sitio web correspondiente y *no* a través de una cartera digital.

.Pasos
. En BlueXP, haga clic en *Sincronizar > licencias*.
. Haga clic en *Agregar licencia* y agregue la información necesaria:
+
.. Introduzca el número de serie.
.. Seleccione la cuenta del sitio de soporte de NetApp asociada con la licencia que va a añadir.
.. Haga clic en *Agregar*.




.Resultado
Cloud Sync actualiza la licencia existente con la nueva fecha de caducidad.
